version: "3.9"

services:
  nextcloud:
    image: nextcloud:29
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.dealmeida.cloud`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-network"
    depends_on:
      - nextcloud-postgres
      - redis
    networks:
      - traefik-network

  nextcloud-postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nc
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  nextcloud-postgres:

networks:
  traefik-network:
    external: true
