version: "3.9"

services:
  nextcloud:
    image: nextcloud:29
    container_name: nextcloud
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.dealmeida.cloud`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
    depends_on:
      - nextcloud-postgres
      - redis
    networks:
      - traefik-net
      - nextcloud-net

  nextcloud-postgres:
    image: postgres:16
    container_name: nextcloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: nextcloud-postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nc
      POSTGRES_PASSWORD: postgres
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
    networks:
      - nextcloud-net

  redis:
    image: redis:7
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud-net

volumes:
  nextcloud-postgres:

networks:
  traefik-net:
    external: true
  nextcloud-net:
    driver: bridge
