version: "3.9"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    container_name: immich-server
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./library:/usr/src/app/upload
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.dealmeida.cloud`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      # Well known for ACME HTTP challenge
      - "traefik.http.routers.immich-wellknown.rule=Host(`immich.dealmeida.cloud`) && PathPrefix(`/.well-known/immich`)"
      - "traefik.http.routers.immich-wellknown.entrypoints=websecure"
      - "traefik.http.routers.immich-wellknown.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich-wellknown.loadbalancer.server.port=2283"
    ports:
      - "2283:2283"
    depends_on:
      immich-postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - traefik-net
      - immich-net

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'
    shm_size: 128mb
    volumes:
      - immich-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U immich"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - immich-net

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich_microservices
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./library:/usr/src/app/upload
    command: ["start.sh", "microservices"]
    depends_on:  
      immich-postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - immich-net


  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich_ml
    restart: unless-stopped
    networks:
      - immich-net

  redis:
    image: redis:7
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - immich-net

volumes:
  immich-postgres:

networks:
  traefik-net:
    external: true
  immich-net:
    driver: bridge

